title: Kevin Allen
email: kevjallen16@gmail.com
description: >- 
  Engineer and consultant from Cleveland, Ohio
url: site.kevjallen.com
twitter_username: kevjallen
github_username: kevjallen

theme: minima
plugins:
  - jekyll-feed

exclude:
  - LICENSE
  - README.md
