title: Kevin Allen

theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed

defaults:
  - scope: 
      path: assets/img
    values:
      image: true
  - scope:
      path: assets/js
    values:
      script: true

include:
  - _pages

exclude:
  - LICENSE
  - README.md
